[package]
name = "ckb-metrics-service"
version = "0.102.0-pre"
license = "MIT"
authors = ["Nervos <dev@nervos.org>"]
edition = "2021"
description = "The service which handle the metrics data in CKB."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-metrics-config = { path = "../metrics-config", version = "= 0.102.0-pre" }
ckb-logger = { path = "../logger", version = "= 0.102.0-pre" }
ckb-async-runtime = { path = "../runtime", version = "= 0.102.0-pre" }
ckb-util = { path = "..", version = "= 0.102.0-pre" }
opentelemetry-prometheus = "0.8"
prometheus = "0.12"
hyper = { version = "0.14", features = ["http1", "tcp", "server"] }
