[package]
name = "ckb-util"
version = "0.102.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "CKB utilities library."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
parking_lot = "0.11"
linked-hash-map = "0.5"
regex = "1.1.6"
once_cell = "1.8.0"

[dev-dependencies]
ckb-fixed-hash = { path = "fixed-hash", version = "= 0.102.0-pre" }

[features]
deadlock_detection = ["parking_lot/deadlock_detection"]
